### ISSUE TITLE
Only trigger when issue not on a board?

### ISSUE THREAD

**Issue by hugovk** [alex-page/github-project-automation-plus#17]
Is it possible to limit an action to only trigger when an issue is _not_ already on a project board?

# Use case

We have two boards: a "Backlog" and a "Task board".

We have an `issue_opened.yml` workflow to automate adding new issues to the backlog's "New issue" column:

```yml
on: issues
name: Issue opened
jobs:
  addToProject:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        if: github.event.action == 'opened'
        uses: alex-page/github-project-automation-plus@master
        with:
          project: Backlog
          column: New issue
          repo-token: ${{ secrets.GH_PAT }}
```

We then groom the backlog as usual, and manually move them to the task board during planning. So far, so good.

Occasionally, we create a new issue and want to put it directly on the task board ("To do" column). And usually we'll manually assign the issue to the board before the automation runs.

When the action runs, it errors:

```
❌ Add issue to project
Run alex-page/github-project-automation-plus@master
##[error]GraphqlError: The card and column must be in the same project
##[error]The card and column must be in the same project
##[error]Node run failed with exit code 1
```

That's not such a huge problem, it doesn't actually move the issue, which is good. What is annoying is some team members receive emails that the run failed.

Is it be possible to for us to add a rule like:

* Only run if issue not on a board

Or something else?

Thank you!
