### ISSUE TITLE
Move card based on number of assignees

### ISSUE THREAD

**Issue by affrae** [alex-page/github-project-automation-plus#32]
Hi Would love to have support for issue:unassigned and pull_request:unassigned events to be able to more a project card inoit a defined column. Something like:

``` yml
name: Move unassigned pull requests into To do

on:
  pull_request:
    types: [unassigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.2.2
        with:
          project: Backlog
          column: To do
          minimumAssignees: 2
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
where `minimumAssignees` is a value such that if the number of assignees falls below that value the card is shifted (default 1)

I want to use this action in my demos... 💜
