### ISSUE TITLE
[error] Cannot read property 'repository' of null

### ISSUE THREAD

**Issue by Altafard** [alex-page/github-project-automation-plus#36]
Why can I get this error?

I use this configuration
```yml
name: Move assigned issue into WIP

on:
  issues:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.2.2
        with:
          project: Board
          column: In Progress
          repo-token: ${{ secrets.GH_SECRET }}
```
