### ISSUE TITLE
Run workflow when certain label is added

### ISSUE THREAD

**Issue by Ionaru** [alex-page/github-project-automation-plus#4]
I'd like any issues with the `Bug` label to be automatically moved into the Bugs project.
Is this possible with this tool?

**Comment by alex-page** [comment]
To put any issue that is labeled into a project. You can start to get this by using the webhooks:
```yml
if: github.event_name == 'issues' && github.event.action == 'labeled'
```

GitHub projects then provides the ability to filter cards by label:
https://github.com/orgs/govau/projects/7?card_filter_query=label%3A%22good+first+issue%22

---

To do the exact way that you describe you would have to fork this project and add a new `with` option:
```yml
 with:
          project: Backlog
          column: Triage
          label: Bug
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

Then when you get the data from the issue you can check if the label matches the label provided. You can do this in this part of the code:
https://github.com/alex-page/github-project-automation-plus/blob/387656da4a6e108ebfc8dfcbfb0300deeb8ec9f0/index.js#L10-L26

If you want some help let me know 👍
