### ISSUE TITLE
Move the issue from specific column only

### ISSUE THREAD

**Issue by Altafard** [alex-page/github-project-automation-plus#41]
Hi, @alex-page! What do you think about it?
In my case I have a column 'To pull' with unassigned issues. And I want to move issue to column 'In progress' on assigning. After closing  issue in column 'In progress' it must appear in 'Done'. But sometimes people assign themselves on closed issues and this issues turn back to the column 'In progress'.

Is it good idea to add new argument 'from column' and move issue only if it is in this column right now?

**Comment by alex-page** [comment]
Hey @Altafard this is a great idea. I think it should be quite straight forward to implement. Would you be interested in making a pull request? Happy to give more direction.

**Comment by BobbyRBruce** [comment]
I too would benefit from this feature. In my case when a PR is created it's added to a column called "New". Things in "New" should stay there until I've had a chance to look at them. We effectively triage new PRs, add labels, ensure the correct people are assigned, etc, then we move them to another column manually. My use of this Action is so if a PR is updated it's moved to the column "Updated" automatically. Unfortunately, if someone creates a PR, then immediately updates it (fairly common), it's moved from "New" to "Updated". I want to stop this.

Something like this would be great for me:

```yml
jobs:
    move-to-updated:
        name: "Move to Updated"
        runs-on: ubuntu-latest
        steps:
            - uses: alex-page/github-project-automation-plus@v0.8.3
              with:
                project: "PR Status Board"
                column: "Updated"
                exclude-in-columns: ["New"]
                repo-token: ${{ secrets.GITHUB_TOKEN }}
```

In the meantime is there a workaround? I'm trying to find the right `if` to stop the job being run if the PR is in the column "New" but it alludes me.
