### ISSUE TITLE
Handling multiple projects

### ISSUE THREAD

**Issue by kammce** [alex-page/github-project-automation-plus#46]
I have multiple projects and I want the column action to move a card is already in a project, to a specific column within that project. If the card does not have a project than no action occurs or I can send it to a "unassigned" project, if I need to have some field available.

**Comment by alex-page** [comment]
That is a great idea. Thanks @kammce. I think this should be quite easy, we pass an array of projects and run the action for each one. Would you be interested in making a PR?

**Comment by kammce** [comment]
When I get free time I'll see if I can make that happen.

**Comment by germanfr** [comment]
I have multiple projects with the same structure in my organization and I'd love if I could leave the project field empty so that it automatically moved it to a column of the same project the issue is currently in, so that I could reuse the same yml file in all the repos and projects.

```yml
name: Move assigned issues into In progress

on:
  issues:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: * <-- something like this or make it optional
          column: In Progress
          repo-token: ${{ secrets.GH_ACTIONS_TOKEN }} 
```
