### ISSUE TITLE
Workflow doesn't work when pull_request is opened from a forked repo

### ISSUE THREAD

**Issue by BobAnkh** [alex-page/github-project-automation-plus#47]
I'm trying to use your actions to automatically add a new pr to the project @alex-page .

Here is my workflow file:

```yaml
name: Assign PullRequest to Project
on:
  pull_request:
    types: [opened, reopened]
jobs:
  assignToProject:
    name: Assign PullRequest to Project
    runs-on: ubuntu-latest
    steps:
      - name: Assign PullRequest to Project Linux command
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: Linux command
          COLUMN: In progress
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
```

When I open a pr myself, it works fine. Here is the log:

```text
Assign PullRequest to Project Linux command1s
    repo-token: ***
Run alex-page/github-project-automation-plus@v0.2.4
  with:
    project: Linux command
    column: In progress
    repo-token: ***
✅ Card materialised into In progress in Linux command
```

When my friend opens a pr, it doesn't work . Here is the log:
```text
 Assign PullRequest to Project Linux command1s
    column: In progress
Run alex-page/github-project-automation-plus@v0.2.4
  with:
    project: Linux command
    column: In progress
##[error]Parameter token or opts.auth is required
```

Are there some things I forgot to configure or wrongly configured? Or does it mean that a pr opened from a forked repo cannot be automatically move into a project using this action?

Could you help me to solve this problem?
