### ISSUE TITLE
Project board column change

### ISSUE THREAD

**Issue by woodie** [alex-page/github-project-automation-plus#48]
If we want to sync our Github project board with external systems, it would be helpful to have a way to trigger actions when an Issue is dragged from one column to another.

**Comment by alex-page** [comment]
I want to keep this action simple and focused on the issue and pull request webhooks. I could expand it to use [column webhooks](https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#project_column). This would address this need. Would you be interested in helping adding this functionality?

**Comment by woodie** [comment]
Contacting an external API adds a log of complexity, but we could instead just add a structured comment on the Issue. There are already lots of integrations that replicate Github Issue comments to external project tracking tools.

**Comment by woodie** [comment]
```
curl -H "Accept: application/vnd.github.mockingbird-preview+json" \ 
https://api.github.com/repos/woodie/next-caltrain-pwa/issues/10/timeline

[
  {"event": "moved_columns_in_project"},
  {"event": "moved_columns_in_project",
  }
]

curl -H "Accept: application/vnd.github.starfox-preview+json" 
https://api.github.com/repos/woodie/next-caltrain-pwa/issues/events/3645053133

{
  "project_card": {
    "column_name": "In Progress",
    "previous_column_name": "Defined Tasks"
  },
}

curl -H "Accept: application/vnd.github.starfox-preview+json" 
https://api.github.com/repos/woodie/next-caltrain-pwa/issues/events/3645473342

{
  "project_card": {
    "column_name": "Defined Tasks",
    "previous_column_name": "In Progress"
  },
}
```

**Comment by woodie** [comment]
https://user-images.githubusercontent.com/17495/90350151-0b6c9800-dff1-11ea-810d-a75131726c7e.png
```
curl -X POST -u next-ct-bot:$GITHUB_TOKEN \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/woodie/next-caltrain-pwa/issues/10/comments \
  -d '{"body":"@woodie moved from **In Progress** to **Defined Tasks**"}' 
```

**Comment by woodie** [comment]
The workflow could look something like this.
```yml
name: Comment when issue moves columns

on:
  issues:
    types: [moved_columns_in_project]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.2.5
        with:
          project: Next Caltrain
          body: '@{actor.login} moved from **{project_card.previous_column_name}** to **{project_card.column_name}**'
          repo-token: ${{ secrets.AUTOMATION_TOKEN }}
```

**Comment by alex-page** [comment]
This is awesome, thanks @woodie. I don't have time right now to implement this but this details is really awesome. If you want to make a PR I can definitely review it.

**Comment by woodie** [comment]
Got it working with existing actions.
```yml
name: Comment on column move

on:
  project_card:
    types: [moved]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch card properties
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: ${{ github.event.project_card.url }}
          CONFIGURATION: |
            { "method": "GET",
              "headers": {
                "Authorization": "Bearer ${{ secrets.AUTOMATION_TOKEN }}",
                "Accept": "application/vnd.github.inertia-preview+json"
              }
            }
      - name: Parse content URL
        uses: jungwinter/split@v1
        id: split
        with:
          msg: ${{ fromJson(env['FETCH_API_DATA']).content_url }}
          seperator: '/'
      - name: Fetch column properties
        uses: JamesIves/fetch-api-data-action@releases/v1
        with:
          ENDPOINT: ${{ github.event.project_card.column_url }}
          CONFIGURATION: |
            { "method": "GET",
              "headers": {
                "Authorization": "Bearer ${{ secrets.AUTOMATION_TOKEN }}",
                "Accept": "application/vnd.github.inertia-preview+json"
              }
            }
      - name: Create comment
        if: ${{ steps.split.outputs._6 == 'issues' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ steps.split.outputs._7 }}
          body: "@${{ github.event.sender.login }} moved Issue to ${{ fromJson(env['FETCH_API_DATA']).name }}"
```
