### ISSUE TITLE
Add Workflow options for specific users

### ISSUE THREAD

**Issue by fharper** [alex-page/github-project-automation-plus#57]
It would be useful to be able to add an action based on a user, like for the `assigned` type.

**Comment by jurijzahn8019** [comment]
Hi @fharper What exactly is the case? This Action supports all(!) issue events.
You can also check the user's name and execute this action conditionally

```yaml
name: Move assigned pull requests

on:
  pull_request:
    types: [assigned]

jobs:
  move_in_todo:
    runs-on: ubuntu-latest
    if: ${{ github.event.assignee.login == 'theusername' }}
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Backlog
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  
  move_in_progress:
    runs-on: ubuntu-latest
    if: ${{ github.event.assignee.login == 'anotherusername' }}
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: Backlog
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
