### ISSUE TITLE
Acting on pull request review events

### ISSUE THREAD

**Issue by boardfish** [alex-page/github-project-automation-plus#61]
This action works on pull request events. Some of these fall into the remit of PR reviews too, like `review_request_removed`, which is nice. But there are some automations I'd like to develop based on reviews that are received.

GitHub has built-in project column automations for approval, but say for example we'd like to do something with a `Changes Requested` review, like:

```yaml
name: Move Unready Pull Requests to Changes Requested

on:
  pull_request_review:
    types: [submitted]

jobs:
  automate-project-columns:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: "Code Review"
          column: "Changes Requested"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

This doesn't work because the event target isn't a PR or issue. But the PR review event contains the pull request for which the review was made, so it'd be nice if this action could figure that out and do its thing based on that.
