### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by MisterChocker** [alex-page/github-project-automation-plus#68]
For some reason I am unable to get this action to work.

My repo is public and not a fork.

I've also tested another action which did work but has very limited functionalities, this is why I'd like to use this action.

I also tried to include the new permission system to modify the default permissions.
I tried both as job and as workflow variable.
(https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions)

But generally it doesn't seem to be a permission issue tho when looking at the log
![image](https://user-images.githubusercontent.com/1857322/121971012-16f72f80-cd78-11eb-8a1a-dea418839117.png)

The project is called Backlog and the column Triage
![image](https://user-images.githubusercontent.com/1857322/121971073-2f674a00-cd78-11eb-95fa-f250c2ca6e86.png)

At this point I am clueless and thats why I opened this issue :|

Also the Actions permissions
![image](https://user-images.githubusercontent.com/1857322/121971295-b87e8100-cd78-11eb-81dc-88fa3a130d44.png)

Also using a repository secret did not worked `Bad credentials`

This is the content of my yml. (it's the same as the one from your example)

```yml
name: Move new issues into Triage

on:
  issues:
    types: [opened]
    
jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: Backlog
          column: Triage
          repo-token: ${{ secrets.GITHUB_TOKEN }}

```

Let me know if there is anything else you need.
Many thanks in advance!

**Comment by alex-page** [comment]
Can you share a link to your repo 👀

**Comment by MisterChocker** [comment]
My test repo https://github.com/MisterChocker/test_repo

**Comment by alex-page** [comment]
Everything looks right to me 😬, I wonder if anyone else can see what is going wrong.

**Comment by MisterChocker** [comment]
Yeah it does look right, it's really weird that it's not working.

**Comment by alex-page** [comment]
Can you try...
1. Rename the project
2. Update the workflow project name to match

Just to make sure this isn't a weird race condition? That is all I can think it could be 👻

**Comment by MisterChocker** [comment]
I am in bed right now, but I can try it tomorrow.

But I've already created two more/different projects and they also did not worked

**Comment by MisterChocker** [comment]
Renamed the project and changed workflow project name to match.

![image](https://user-images.githubusercontent.com/1857322/122003415-58590080-cdb3-11eb-9eca-79fee22c3158.png)

```yml
name: Move new issues into Triage

on:
  issues:
    types: [opened]
    
jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: TestProject
          column: Triage
          repo-token: ${{ secrets.GITHUB_TOKEN }}

```

Same result

![image](https://user-images.githubusercontent.com/1857322/122003356-48d9b780-cdb3-11eb-9f6a-98cf9d810aad.png)

**Comment by MisterChocker** [comment]
Are you able to reproduce the issue on a new/different repo?

**Comment by MisterChocker** [comment]
Small update: I've now also tried this workflow on our main repo with the same outcome. Other solutions are working tho.

**Comment by Doarakko** [comment]
I also reproduced with public repo and public project.

I solved it by creating and using a token with `repo` permission.

<img width="" src="https://user-images.githubusercontent.com/21009186/123502138-d3a89500-d684-11eb-9185-a842d03bb36f.png">

## Related issue

> `repo` is needed also for public user Projects and public repos
https://github.com/alex-page/github-project-automation-plus/issues/51

**Comment by MisterChocker** [comment]
@Doarakko thanks mate, I'll try with a token with repo permission later!

**Comment by alex-page** [comment]
I have updated the documentation for repository projects. This is super odd though, thanks @MisterChocker and @Doarakko ✨

**Comment by AllanChain** [comment]
I am new to this action and having the same problem. The `GITHUB_TOKEN` definitely has permission `RepositoryProjects: write`. If this action previously worked with `GITHUB_TOKEN` and recently fails, it might be GitHub's issue. (somewhat like actions/starter-workflows#332 ?)  Should we contact GitHub if it is the case?

**Comment by nilsreichardt** [comment]
Any ideas why `GITHUB_TOKEN` is not working?

**Comment by nilsreichardt** [comment]
I created a public repository where I reproduced the issue: https://github.com/nilsreichardt/github-action-project-issue

Workflow:
```
name: new-issue-automation

on:
  issues:
    types: [opened]
    
jobs:
  move-new-issues-to-backlog:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.0
        with:
          project: "Board"
          column: "Backlog"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

The workflow failing with this error:
 ```
Error: Resource not accessible by integration
```
Link to broken workflow: https://github.com/nilsreichardt/github-action-project-issue/runs/3186029884?check_suite_focus=true


It's working with a personal access token, but with the `GITHUB_TOKEN` is not working. Therefore, I contacted the GitHub Support, why it's working with a personal access token, but not with the `GITHUB_TOKEN` (even when `GITHUB_TOKEN` has enough permissions).

I got this response from the GitHub Support:

> Hi there,
> 
> Thank you for contacting GitHub Support.
> 
> I took a look at the workflow and was also able to reproduce it.
> 
> It doesn't look like an issue with GITHUB_TOKEN as I was able to use it on other third-party actions.
> 
> This looks like the issue is related to the action itself. The owners of the action could reach out to GitHub to investigate the issue with them.
> 
> I'm sorry I can't be of more help, do let us know if you need any further assistance.
> 
> Regards,

@alex-page, do you have the time to contact the support as the GitHub support mentioned, so we can find out, why personal access token is working, but `GITHUB_TOKEN` not? My support ticket id is `1253216`.
