### ISSUE TITLE
Workflow run fails when triggered by an `issue_comment` event

### ISSUE THREAD

**Issue by andylolz** [alex-page/github-project-automation-plus#69]
My workflow looks like this:

```yml
name: This fails
on:
  issue_comment:
    types:
      - created
jobs:
  mark-as-updated:
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: Project name
          column: Column name
          repo-token: ${{ secrets.TOKEN }}

```

It fails with the following error message:
```
Error: Cannot read property 'projects' of undefined
```

If I instead trigger it using e.g.:
```yml
on:
  issues:
    types:
      - opened
```

…it works fine.

I’m not exactly sure, but I wonder if the problem is this line:

https://github.com/alex-page/github-project-automation-plus/blob/8b1f15391cdb58c0c6a4ee4a83f5819cf3e747df/src/generate-project-query.js#L11
