### ISSUE TITLE
Project not found - Classic project

### ISSUE THREAD

**Issue by BennyDeBock** [alex-page/github-project-automation-plus#81]
So I have been working on creating a workflow to put issues with the good first issue label onto a project board.

I've managed to make this work in an organisation, but it doesn't seem to work when using a public repository with a user project not belonging to an organisation.

https://github.com/BennyDeBock/test-gh-actions/runs/7598890181?check_suite_focus=true

https://github.com/users/BennyDeBock/projects/1/views/1

Here is the workflow I'm using.
https://github.com/BennyDeBock/test-gh-actions/blob/main/.github/workflows/project-board.yml

Is there something I'm doing wrong? or somewhere that i'm able to specify the url to the project?
@alex-page

**Comment by wnqueiroz** [comment]
I have a similar problem here, only in a private context... I'm trying to automate moving issues for a project within an organization. The repository and project are private. What am I doing wrong?

I configured the personal access token scopes in the link:

https://github.com/settings/tokens/new?scopes=repo,write:org&description=PERSONAL_ACCESS_TOKEN

My workflow is set up in an even simpler way:

```yaml
name: "Foo"

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Foo
          column: Bar
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
```

I've also enabled SSO on the token...

Screenshot:

![image](https://user-images.githubusercontent.com/22847781/189372713-31f7d35a-fb5c-4826-9805-5e74c9ef8548.png)

**Comment by SirMishaa** [comment]
Any up ?

**Comment by BennyDeBock** [comment]
@SirMishaa Here you can see a working example I made in the past for the Vapor organisation https://github.com/vapor/ci/blob/main/.github/workflows/issues-to-project-board.yml

**Comment by Neehal-ATD** [comment]
I have this same problem, and I looked at the action failure logs. Looks like Node.js needs an upgrade, although I'm pretty new to all this so not sure if it's something I can do on my end or the action code's end.

![image](https://user-images.githubusercontent.com/123143770/215255473-343d0521-f413-4abd-886e-e29853d39500.png)

**Comment by alex-page** [comment]
@Neehal-ATD it looks like we need to change the supported NodeJS versions on this package.

**Comment by alex-page** [comment]
@Neehal-ATD this action supports NodeJS 16 as a minimum. See the latest commit into the repository.

**Comment by Neehal-ATD** [comment]
@alex-page Ah ok I think I found the issue; I'd copied the code from the examples you had on the GitHub Marketplace page which had v0.8.1 listed in the syntax. 🤦‍♂️Didn't really check if it was the latest version.
You can maybe update the version number on there. Thanks for the response, would not have realised otherwise 😆

**Comment by alex-page** [comment]
Updated the docs. Thanks Neehal!

**Comment by Steph-crown** [comment]
@wnqueiroz, were you able to get the workflow to work? I get the same error as you did when I tried to use the workflow to move issues to a project in a private organization.

```
Run alex-page/github-project-automation-plus@v0.8.3
  with:
    project: Test Project
    column: In Progress
    repo-token: ***
    action: update
Error: Could not find the column "In Progress" or project "Test Project"
```

**Comment by OscarCasadoLorenzo** [comment]
Same issue as @wnqueiroz and @Steph-crown .
@alex-page Do you know how to solve this problem?

**Comment by ianwesleyarmstrong** [comment]
Also ran into this with `v0.8.3`.

**Comment by alex-page** [comment]
I don't know how to solve this problem, I would have to dig through the API docs and replicate it myself. There might be some issues with the logic to find projects as it is meant to check your org and own repos. This might have been changed recently.

**Comment by Steph-crown** [comment]
There is a possibility that this issue arises when using it with Beta projects.

**Comment by aptalca** [comment]
Is this action working with the new projects? I don't believe they're beta anymore. They are called `projects` or `all new projects` and the legacy ones are called `classic projects`.

Github deprecated the classic projects and it won't let you create new ones unless you already have existing classic projects.

Thanks

**Comment by alex-page** [comment]
The new projects have a lot of automation already built into them. I am unsure if this action is needed for them.

**Comment by stilnat** [comment]
same issue with  0.8.3 
I tried to run the below job but that fails with `Could not find the column "Triage" or project "Logs"`.
I have a public project called "Logs" with a "Triage" column in it.
My repo is public, [here's the link](https://github.com/stilnat), it was made just for testing this.
Let me know if someone knows what I'm doing wrong !

```
name: Move new issues into Triage

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Backlog
          column: Triage
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
