### ISSUE TITLE
[error] Cannot read property 'repository' of null 

### ISSUE THREAD

**Issue by RhoderickGalero** [alex-page/github-project-automation-plus#87]
I saw a similar issue 
https://github.com/alex-page/github-project-automation-plus/issues/36
but it didnt resolve my issue 

I have the script below which is basically moving assigned issue to In Progress 

```
name: GitHub Project Automation+

on:
  issues:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: RhoderickGalero's Practice
          column: In Progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```
 I get this error
1s
1s
Run alex-page/github-project-automation-plus@v0.8.3
  with:
    project: RhoderickGalero
    column: In Progress
    repo-token: ***
    action: update
Error: Cannot read properties of null (reading 'repository')

My repository and Project are both public

Appreciate the help
