### ISSUE TITLE
Move issues to In Review

### ISSUE THREAD

**Issue by frehburg** [alex-page/github-project-automation-plus#89]
Hey, i would like to move the issue card to my own column that I called 'In Review' when a pull request is opened. I am however not exactly sure how the github action should look like then. Can you help me out please?

**Comment by frehburg** [comment]
https://docs.github.com/en/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards

**Comment by frehburg** [comment]
It does not seem to work like this:
```
name: Move opened pull requests into In Review

on:
  pull_request:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: ERKER2Phenopackets kanban
          column: In Review
          repo-token: ${{ secrets.GITHUB_TOKEN }}
```

This is the result of the action run: https://github.com/BIH-CEI/ERKER2Phenopackets/actions/runs/6039022029/job/16386725239?pr=37

![image](https://github.com/alex-page/github-project-automation-plus/assets/43171336/6965328a-d3ca-4edd-9a8d-5d3a83d0dde6)
